substitutions:
  node_name: IKEA
  GPIO_RGB_LED: GPIO25
  I2C_SCL: GPIO22
  I2C_SDA: GPIO21
  SCD4x_update_interval: 60s
  ADC_update_interval: 60s
  aqi_co2_ideal_good: "600"
  aqi_co2_max_good: "800"
  aqi_co2_ideal_acceptable: "1000"
  aqi_co2_max_acceptable: "1200"
  aqi_pm2_5_avg_24h_max_good: "12"
  aqi_pm2_5_avg_24h_max_acceptable: "25"  # WHO 2006
  aqi_message_bad: "Bad"
  aqi_message_acceptable: "Acceptable"
  aqi_message_good: "Good"
  pm1006_pin_rx: GPIO16
  pm1006_pin_tx: GPIO17
  pm1006_update_interval: 5s
  sensor_fan: GPIO12
  temp_calibration: "-4"

esphome:
  name: ikea-semafor
  on_boot:
    priority: -10
    then:
      - light.turn_on: 
          id: led_rgb
          brightness: 30%
esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "type your own"

ota:
  password: "8b73f0e42cc0038d8a5c1abecb2de6dd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${node_name} Fallback Hotspot"
    password: "jz9Dc4gerk7s"

bluetooth_proxy:
  active: true

light:
  - id: led_rgb
    internal: False
    platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: $GPIO_RGB_LED
    num_leds: "3"
    method: ESP32_I2S_1
    name: "RGB LED indicator"
    effects:
      - addressable_lambda:
          name: "AQI Level (step change)"
          update_interval: 25ms
          lambda: |-  
            if (id(aqi).state == "Bad") {
              it.all() = ESPColor(255,0,0); //red color
            } else if (id(aqi).state == "Acceptable") {
              it.all() = ESPColor(255,255,0); 
            } else if (id(aqi).state == "Good") {
              it.all() = ESPColor(0,255,0); //green color
            } else {
              it.all() = ESPColor(255,255,255); //white color
            }
      - addressable_lambda:
          name: "AQI Level (smooth change)"
          update_interval: 25ms
          lambda: |-
            
            static int red = 0;
            static int green = 0;

            if (id(co2_value).state <= ${aqi_co2_ideal_good}) {
              red = 0;
              green = 255;
            } else if ((id(co2_value).state > ${aqi_co2_ideal_good}) && (id(co2_value).state <= 1000)) {
              red = ceil(((id(co2_value).state) - ${aqi_co2_ideal_good}) * (255.0/(${aqi_co2_ideal_acceptable} - ${aqi_co2_ideal_good})));
              green = 255;
              
            } else if ((id(co2_value).state > 1000) && (id(co2_value).state < 1200)) {
              red = 255;
              green = 255 - ceil((id(co2_value).state - 1000) * (255.0/200));

            } else if (id(co2_value).state >= 1200) {
              red = 255;
              green = 0;
            }
          
            it.all() = ESPColor(red,green,0);

script:
  - id: evaluate_air_quality
    then:
      - logger.log: "Fan is ON"
      - switch.turn_on: fan
      - logger.log: "Waiting 10s"
      - delay: 10s
      - sensor.template.publish:
          id: pm2_5_value
          state: !lambda return id(pm2_5_value).state;
      - logger.log: "Fan is OFF"
      - switch.turn_off: fan
      - if:
          condition:
            - lambda: 'return isnan(id(co2_value).state);'
          then:
            - logger.log: "Waiting for CO2 sensor"
          else:
            - logger.log: "CO2 sensor is ready"
            - script.execute: update_aqi

  - id: update_aqi
    mode: restart
    then:
      # Bad if at least one of the sensor values is bad
      - if:
          condition:
            or:
              - lambda: 'return (id(co2_value).state > ${aqi_co2_max_acceptable});'
              - sensor.in_range:
                  id: pm2_5_avg_24h
                  above: ${aqi_pm2_5_avg_24h_max_acceptable}
          then:
            - text_sensor.template.publish:
                id: aqi
                state: ${aqi_message_bad}
          else:
            # Acceptable if at least one of the sensor values is acceptable
            - if:
                condition:
                  or:
                    - lambda: 'return (id(co2_value).state > ${aqi_co2_max_good});'
                    - sensor.in_range:
                        id: pm2_5_avg_24h
                        above: ${aqi_pm2_5_avg_24h_max_good}
                then:
                  - text_sensor.template.publish:
                      id: aqi
                      state: ${aqi_message_acceptable}
                else:
                  # Otherwise good (all of the sensor values are good)
                  - text_sensor.template.publish:
                      id: aqi
                      state: ${aqi_message_good}

switch:
  - platform: gpio
    pin: $sensor_fan
    id: fan
    name: "${node_name} ventilátor"
    internal: true
    icon: mdi:fan
    entity_category: config
  - platform: restart
    name: "${node_name} restart"
  
i2c:
  - id: bus_a
    sda: $I2C_SDA
    scl: $I2C_SCL
    scan: True

uart:
  rx_pin: ${pm1006_pin_rx}
  tx_pin: ${pm1006_pin_tx}
  baud_rate: 9600

sensor:
  - platform: scd4x
    i2c_id: bus_a
    id: co2_sensor
    address: 0x62
    update_interval: ${SCD4x_update_interval}
    automatic_self_calibration: true
    co2:
      name: "${node_name} CO₂"
      id: co2_value
    temperature:
      name: "${node_name} teplota"
      id: temp_value
      filters:
        offset: ${temp_calibration}

    humidity:
      name: "${node_name} vlhkost"
      id: humi_value
  - platform: pm1006
    pm_2_5:
      name: "${node_name} PM2.5"
      id: pm2_5_value
      internal: false
    update_interval: 2min
  - platform: template
    name: "${node_name} PM2.5 24h average"
    id: pm2_5_avg_24h
    icon: mdi:blur
    unit_of_measurement: µg/m³
    lambda: |-
      return id(pm2_5_value).state;
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 1440  # = 24 hours x 60 minutes
          send_every: 1
    on_value:
      then:
        - script.execute: update_aqi
  - platform: wifi_signal
    name: "${node_name} WiFi Signal"
    entity_category: diagnostic
    disabled_by_default: true


# A textual presentation of the AQI: good, acceptable, bad
text_sensor:
  - platform: template
    name: "${node_name} Air Quality Index"
    id: aqi
    icon: mdi:air-filter
  - platform: wifi_info
    ip_address:
      name: "${node_name} IP Address"
      entity_category: diagnostic
      disabled_by_default: true
    ssid:
      name: "${node_name} Connected SSID"
      entity_category: diagnostic
      disabled_by_default: true
    bssid:
      name: "${node_name} Connected BSSID"
      entity_category: diagnostic
      disabled_by_default: true
    mac_address:
      name: "${node_name} Mac Wifi Address"
      entity_category: diagnostic
      disabled_by_default: true
    scan_results:
      name: "${node_name} Latest Scan Result"
      entity_category: diagnostic
      disabled_by_default: true

font:
  - file: 'fonts/arial.ttf'
    id: font1
    size: 14
    glyphs:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "0"
      - " "
      - "nan"
      - "µg/m³"
      - "ppm"
      - "°C"
      - "%"

number:
  - platform: template
    name: "${node_name} kontrast displeje"
    id: DISPLAY_contrast
    icon: "mdi:contrast-circle"
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    on_value:
      then:
        lambda: |-
          if (id(DISPLAY_contrast).state) {
            id(oled_display).set_contrast(x / 100);
          } else {
            id(oled_display).set_contrast(0.5);
          }

interval:
  - interval: 1min
    then:
      - script.execute: evaluate_air_quality
    
display:
  - platform: ssd1306_i2c
    id: oled_display
    model: "SSD1306 128x32"
    lambda: |-
        it.printf(0, 0, id(font1), "%.0f ppm", id(co2_value).state);
        it.printf(0, 16, id(font1), "%.0f µg/m³", id(pm2_5_value).state);        
        it.printf(126, 0, id(font1), TextAlign::TOP_RIGHT, "%.0f °C", id(temp_value).state);
        it.printf(126, 16, id(font1), TextAlign::TOP_RIGHT, "%.0f %%", id(humi_value).state);
